#!/usr/bin/env bash

# Copyright (C) 2009-2017 Lightbend Inc. <https://www.lightbend.com>

# Build script for executing tests on CI

set -e
set -o pipefail

SBT=$(which sbt)

if [ $? -ne 0 ]; then
    echo "sbt not found on PATH."
    exit 1
fi

# Drivers paths and configurations
GECKODRIVER_PATH=$(which geckodriver)
if [ $? -ne 0 ]; then
    echo "geckodriver not found on PATH."
    exit 1
fi

CHROMEDRIVER_PATH=$(which chromedriver)
if [ $? -ne 0 ]; then
    echo "chromedriver not found on PATH."
    exit 1
fi

GECKODRIVER_PROPERTY="-Dwebdriver.gecko.driver=$GECKODRIVER_PATH"
CHROMEDRIVER_PROPERTY="-Dwebdriver.chrome.driver=$CHROMEDRIVER_PATH"

export JVM_OPTS="-Xmx2G -Xss2M -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=192M -Dfile.encoding=UTF-8"

# There are lots of different ways to configure the memory with sbt, and not every sbt installation supports
# all of them, eg on Travis, sbt doesn't support the -mem option. But JAVA_OPTS should be standard across
# the board.
export JAVA_OPTS="$JVM_OPTS $CHROMEDRIVER_PROPERTY $GECKODRIVER_PROPERTY"

build() {
  "$SBT" --warn "$@" | grep --line-buffered -v 'Resolving \|Generating \|addons\.\|GConf-WARNING'
}