#!/usr/bin/env bash

# Copyright (C) 2009-2017 Lightbend Inc. <https://www.lightbend.com>

# Build script for executing tests on CI

set -e
set -o pipefail

SBT=$(which sbt)

if [ $? -ne 0 ]; then
    echo "sbt not found on PATH."
    exit 1
fi

# Use travis scala version or defaults to 2.12.6 which is the `scalaVersion` configured in build.sbt
SCALA_VERSION=${TRAVIS_SCALA_VERSION:-"2.12.6"}

# There are lots of different ways to configure the memory with sbt, and not every sbt installation supports
# all of them, eg on Travis, sbt doesn't support the -mem option. But JAVA_OPTS should be standard across
# the board.
export JAVA_OPTS="-Xmx2G -Xss2M -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=192M -Dfile.encoding=UTF-8"

# Enable scripts to configure some additional arguments that will be passed to sbt.
ADDITIONAL_SBT_ARGUMENTS=${ADDITIONAL_SBT_ARGUMENTS:-""}

build() {
  "$SBT" ${ADDITIONAL_SBT_ARGUMENTS} ++${SCALA_VERSION} "$@" | grep --line-buffered -v 'Resolving \|Generating \|addons\.\|GConf-WARNING'
}
