#!/usr/bin/env bash

# Copyright (C) 2009-2017 Lightbend Inc. <https://www.lightbend.com>

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"$SCRIPTS_DIR/test"         || exit 1
"$SCRIPTS_DIR/testDocs"     || exit 1
"$SCRIPTS_DIR/validateDocs" || exit 1
"$SCRIPTS_DIR/validateCode" || exit 1
