#!/usr/bin/env bash

# Copyright (C) 2009-2017 Lightbend Inc. <https://www.lightbend.com>

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/build"

build "scalafmtCheckAll scalafmtSbtCheck" || (
    echo "[error] ERROR: Scalafmt test failed."
    echo "[error] To fix, format your sources using 'sbt scalafmtAll scalafmtSbt' before submitting a pull request."
    echo "[error] Additionally, please squash your commits (eg, use git commit --amend) if you're going to update this pull request."
    false
  )

build mimaReportBinaryIssues
