#!/usr/bin/env bash

# Copyright (C) 2009-2017 Lightbend Inc. <https://www.lightbend.com>

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/build"

build docs/validateDocs docs/scalafmtCheckAll docs/scalafmtSbtCheck
